
name: hello-world
on:
  schedule:
    - cron: '*/10 * * * *' # run each monday at 10 AM UTC
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: my-step
        run: echo "Hello World!"